#!highlight yaml

heat_template_version: 2013-05-23

resources:
# Creating allow action
    demo_act:
        type: OS::Neutron::PolicyAction
        properties:
            name: demo_act
            action_type: allow
           shared: False

    demo_act_dup:
        type: OS::Neutron::PolicyAction
        properties:
            name: demo_act_dup
            action_type: allow
           shared: False

# Creating a classifier,policy-rule,policy-ruleset(Contract) for any tcp traffic
    demo_class_any_tcp:
        type: OS::Neutron::PolicyClassifier
        properties:
            name: demo_class_any_tcp
            protocol: tcp
            direction: in
            shared: False

    demo_rule_any_tcp:
        type: OS::Neutron::PolicyRule
        properties:
            name: demo_rule_any_tcp
            policy_classifier_id: { get_resource: demo_class_any_tcp }
            policy_actions: [{ get_resource: demo_act }]
            shared: False

    demo_ruleset_any_tcp:
        type: OS::Neutron::PolicyRuleSet
        properties:
            name: demo_ruleset_any_tcp
            policy_rules: [{ get_resource: demo_rule_any_tcp }]
            child_policy_rule_sets: []
            shared: False

# Creating a classifier,policy-rule,policy-ruleset(Contract) for any udp traffic
    demo_class_any_udp:
        type: OS::Neutron::PolicyClassifier
        properties:
            name: demo_class_any_udp
            protocol: udp
            direction: in
            shared: False

    demo_rule_any_udp:
        type: OS::Neutron::PolicyRule
        properties:
            name: demo_rule_any_udp
            policy_classifier_id: { get_resource: demo_class_any_udp }
            policy_actions: [{ get_resource: demo_act }]
            shared: False

    demo_ruleset_any_udp:
        type: OS::Neutron::PolicyRuleSet
        properties:
            name: demo_ruleset_any_udp
            policy_rules: [{ get_resource: demo_rule_any_udp }]
            child_policy_rule_sets: []
            shared: False

# Creating a classifier,policy-rule,policy-ruleset(Contract) for ICMP traffic
    demo_class_icmp:
        type: OS::Neutron::PolicyClassifier
        properties:
            name: demo_class_icmp
            protocol: icmp
            direction: bi
            shared: False

    demo_rule_icmp:
        type: OS::Neutron::PolicyRule
        properties:
            name: demo_rule_icmp
            policy_classifier_id: { get_resource: demo_class_icmp }
            policy_actions: [{ get_resource: demo_act }]
            shared: False

    demo_ruleset_icmp:
        type: OS::Neutron::PolicyRuleSet
        properties:
            name: demo_ruleset_icmp
            policy_rules: [{ get_resource: demo_rule_icmp }]
            child_policy_rule_sets: []
            shared: False

# Creating a classifier,policy-rule,policy-ruleset(Contract) for allow all protocol(ICMP,TCP,UDP)

    demo_class_all:
        type: OS::Neutron::PolicyClassifier
        properties:
            name: demo_class_icmp
            protocol: [icmp,tcp,udp]
            direction: bi
            shared: False

    demo_rule_all:
        type: OS::Neutron::PolicyRule
        properties:
            name: demo_rule_all
            policy_classifier_id: { get_resource: demo_class_all }
            policy_actions: [{ get_resource: demo_act }]
            shared: False

    demo_ruleset_all:
        type: OS::Neutron::PolicyRuleSet
        properties:
            name: demo_ruleset_all
            policy_rules: [{ get_resource: demo_rule_all }]
            child_policy_rule_sets: []
            shared: False

# Creating L3Policy,L2Policy and PTG for header SamePTG_SameL2P_SameL3P
    demo_sameptgl2pl3p_l3_policy:
        type: OS::Neutron::L3Policy
        properties:
            name: demo_sameptgl2pl3p_l3p
            ip_pool: "5.5.5.0/24"
            subnet_prefix_length: 28
            shared: False

    demo_sameptgl2pl3p_l2_policy:
        type: OS::Neutron::L2Policy
        depends_on: demo_sameptgl2pl3p_l3_policy
        properties:
            name: demo_sameptgl2pl3p_bd
            l3_policy_id: { get_resource: demo_sameptgl2pl3p_l3_policy }
            shared: False

    demo_sameptgl2pl3p_ptg:
        type: OS::Neutron::PolicyTargetGroup
        properties:
            name: demo_sameptgl2pl3p_ptg
            l2_policy_id: {get_resource: demo_sameptgl2pl3p_l2_policy}
            shared: False

# Creating L3Policy,L2Policy and PTG for header DiffPTG_SameL2P_SameL3P
    demo_diffptgsamel2pl3p_l3_policy:
        type: OS::Neutron::L3Policy
        properties:
            name: demo_diffptgsamel2pl3p_l3p
            ip_pool: "6.6.6.0/24"
            subnet_prefix_length: 28
            shared: False

    demo_diffptgsamel2pl3p_l2_policy:
        type: OS::Neutron::L2Policy
        depends_on: demo_diffptgsamel2pl3p_l3_policy
        properties:
            name: demo_diffptgsamel2pl3p_bd
            l3_policy_id: { get_resource: demo_diffptgsamel2pl3p_l3_policy }
            shared: False

    demo_diffptgsamel2pl3p_ptg:
        type: OS::Neutron::PolicyTargetGroup
        properties:
            name: demo_diffptgsamel2pl3p_ptg
            l2_policy_id: {get_resource: demo_diffptgsamel2pl3p_l2_policy}
            shared: False

# Creating L3Policy,L2Policy and PTG for header DiffPTG_DiffL2P_SameL3P
    demo_diffptgl2psamel3p_l3_policy:
        type: OS::Neutron::L3Policy
        properties:
            name: demo_diffptgl2psamel3p_l3p
            ip_pool: "7.7.7.0/24"
            subnet_prefix_length: 28
            shared: False

    demo_diffptgl2psamel3p_l2_policy:
        type: OS::Neutron::L2Policy
        depends_on: demo_diffptgl2psamel3p_l3_policy
        properties:
            name: demo_diffptgl2psamel3p_bd
            l3_policy_id: { get_resource: demo_diffptgl2psamel3p_l3_policy }
            shared: False

    demo_diffptgl2psamel3p_ptg:
        type: OS::Neutron::PolicyTargetGroup
        properties:
            name: demo_diffptgl2psamel3p_ptg
            l2_policy_id: {get_resource: demo_diffptgl2psamel3p_l2_policy}
            shared: False

# Creating L3Policy,L2Policy and PTG for header DiffPTG_DiffL2P_DiffL3P
    demo_srvr_l3_policy:
        type: OS::Neutron::L3Policy
        properties:
            name: demo_srvr_subnet
            ip_pool: "30.30.30.0/24"
            subnet_prefix_length: 28
            shared: False

    demo_clnt_l3_policy:
        type: OS::Neutron::L3Policy
        properties:
            name: demo_clnt_subnet
            ip_pool: "40.40.40.0/24"
            subnet_prefix_length: 28
            shared: False

    demo_srvr_l2_policy:
        type: OS::Neutron::L2Policy
        depends_on: demo_srvr_l3_policy
        properties:
            name: demo_srvr_bd
            l3_policy_id: { get_resource: demo_srvr_l3_policy }
            shared: False

    demo_clnt_l2_policy:
        type: OS::Neutron::L2Policy
        depends_on: demo_clnt_l3_policy
        properties:
            name: demo_clnt_bd
            l3_policy_id: { get_resource: demo_clnt_l3_policy }
            shared: False

# Create EPGs for DHCP rendering by Admin
    server_ptg:
        type: OS::Neutron::PolicyTargetGroup
        properties:
            name: server_ptg_1
            l2_policy_id: {get_resource: demo_srvr_l2_policy}
            shared: False
            
    client_ptg:
        type: OS::Neutron::PolicyTargetGroup
        properties:
            name: client_ptg_1
            l2_policy_id: {get_resource: demo_clnt_l2_policy}
            consumed_policy_rule_sets:
            shared: False    

outputs:

    server_ptg_id:
        value: { get_resource: server_ptg }

    client_ptg_id:
        value: { get_resource: client_ptg } 

    demo_srvr_l3_policy_id:
        value: { get_resource: demo_srvr_l3_policy }

    demo_clnt_l3_policy_id:  
        value: { get_resource: demo_clnt_l3_policy }

    demo_srvr_l2_policy_id:
        value: { get_resource: demo_srvr_l2_policy }

    demo_clnt_l2_policy_id:
        value: { get_resource: demo_clnt_l2_policy }

    demo_ruleset_tcp_id:
        value: { get_resource: demo_ruleset_tcp }

    demo_rule_any_tcp_id:
        value: { get_resource: demo_rule_any_tcp }

    demo_ruleset_any_udp_id:
        value: { get_resource: demo_ruleset_any_udp }

    demo_rule_any_udp_id:
        value: { get_resource: demo_rule_any_udp }

    demo_ruleset_icmp_id:
        value: { get_resource: demo_ruleset_icmp }

    demo_rule_icmp_id:
        value: { get_resource: demo_rule_icmp }
