#!highlight yaml

# User editable config params
num_comp_nodes: 2
apic_ip: '172.28.184.30'
apic_passwd: 'noir0123'
controller_ip: '172.28.184.35'
ext_rtr: '172.28.184.38'
gwip1_extrtr: '1.102.1.254'
gwip2_extrtr: '1.102.2.254'
#vm_image: '"trusty-multi-if"'
vm_image: 'ubuntu_multi_nics'
# Enable the below flag inorder to live-debug on Failure of a Testcase
pausetodebug: True
