#!highlight yaml

# User editable config params
num_comp_nodes: 2
apic_ip: '172.28.184.30'
apic_passwd: 'noir0123'
controller_ip: '172.28.184.35'
tenant_list: ['ENGG','HRC']
nova_az_name: 'gbp_zone'
az_comp_node: 'f2-compute-2.noiro.lab'
az_nova_comp_node: 'f2-compute-1.noiro.lab'
network_node: '172.28.184.36'
compute-1: '172.28.184.36'
compute-2: '172.28.184.37'
ext_rtr: '172.28.184.38'
gwip1_extrtr: '1.102.1.254'
gwip2_extrtr: '1.102.2.254'
extrtr_ip1: '1.102.1.1'
extrtr_ip2: '1.102.2.1'
vm_image: 'ubuntu_multi_nics'
# Enable the below flag inorder to live-debug on Failure of a Testcase
pausetodebug: False
