#!highlight yaml

# Mandatory: User must not change the below config params
main_setup_heat_temp: '/root/gbpauto/testcases/testcases_integ/heat_integ_config.yaml'
nova_agg_name: 'gbp_agg'
nova_az_name: 'gbp_zone'

# User editable config params
num_comp_nodes: 2
controller_ip: '172.28.184.35'
compnode1_ip: '172.28.184.36'
compnode2_ip: '172.28.184.37'
comp_nodes: ['172.28.184.36','172.28.184.37']
apic_ip: '172.28.184.30'
leaf1_ip: '172.28.184.31'
leaf2_ip: '172.28.184.32'
leaf1name: 'f2-leaf-1'
leaf1_node_id: '201'
leaf2name: 'f2-leaf-2'
leaf2_node_id: '202'
az_comp_node: 'f2-compute-1.noiro.lab'
vm_image: 'ubuntu_multi_nics'
leaf1_to_compnode1_conn: 'eth1/33'
leaf1_to_compnode2_conn: 'eth1/34'
leaf2_to_compnode1_conn: 'eth1/33'
leaf2_to_compnode2_conn: 'eth1/34'
leaf1_to_spine_conn: 'eth1/49'
leaf2_to_spine_conn: 'eth1/49'
pausetodebug: True
